#!/bin/bash

BASEDIR=$(dirname $0)
if [ "$#" -eq 1 ]; then
    java -Dwindow.capacity=$1 -cp $BASEDIR/log-parser/build/libs/log-parser-1.0.jar edu.utdallas.lp.LogParser $BASEDIR/all-bugs.csv $BASEDIR/correct-patches.csv
else
    java -cp $BASEDIR/log-parser/build/libs/log-parser-1.0.jar edu.utdallas.lp.LogParser $BASEDIR/all-bugs.csv $BASEDIR/correct-patches.csv
fi
