#!/bin/bash

if [ "$#" -eq 1 ]; then
    java -Dwindow.capacity=$1 -cp log-parser-1.0.jar edu.utdallas.lp.LogParser all-bugs.csv correct-patches.csv > ./dataset.json
else
    java -cp log-parser-1.0.jar edu.utdallas.lp.LogParser all-bugs.csv correct-patches.csv > ./dataset.json
fi
