#!/bin/bash

outUnmutatedWnd() {
    windowCapacity=$1
    subject=$2
    bugId=$3
    classInternalName=$4
    lineNo=$5
    java -Dwindow.capacity=$windowCapacity -cp window/build/libs/window.jar edu.utdallas.window.App pool/original/$subject/$bugId/$classInternalName".class" $lineNo
}

outMutatedWnd() {
    windowCapacity=$1
    subject=$2
    bugId=$3
    patchNo=$4
    lineNo=$5
    java -Dwindow.capacity=$windowCapacity -cp window/build/libs/window.jar edu.utdallas.window.App pool/cg-mutated/$subject"_"$bugId"_"$patchNo".class" $lineNo
}

windowCapacity=21
if [ "$#" -eq 1 ]; then
    windowCapacity=$1
fi

echo "["
for line in $(cat cg-info.csv); do
    subject=$(echo $line | awk 'BEGIN{FS=","}{print $1}')
    bugId=$(echo $line | awk 'BEGIN{FS=","}{print $2}')
    patchNo=$(echo $line | awk 'BEGIN{FS=","}{print $3}')
    classInternalName=$(echo $line | awk 'BEGIN{FS=","}{print $4}' | sed 's/\./\//g')
    lineNo=$(echo $line | awk 'BEGIN{FS=","}{print $5}')
    buggy=$(outUnmutatedWnd $windowCapacity $subject $bugId $classInternalName $lineNo)
    if [ $buggy != "[]," ]; then
	fixed=$(outMutatedWnd $windowCapacity $subject $bugId $patchNo $lineNo)
	label=$(echo $line | awk 'BEGIN{FS=","}{print $6}')
	echo -e "\t{"
	echo -e "\t\t\"buggy\":$buggy"
	echo -e "\t\t\"fixed\":$fixed"
	echo -e "\t\t\"label\":$label"
	echo -e "\t}"
    fi
done
echo "]"

